### ISSUE TITLE
mount .tiup/ into the control node while using docker in dev mode

### ISSUE THREAD

**Issue by july2993** [pingcap-incubator/tiops#32]
So we can avoid download component  while deploy cluster in the control node

**Comment by lonng** [comment]
You can use TIUP_MIRRORS=/local/mirrors to specify a local mirror repository.

**Comment by lonng** [comment]
You can build a local mirror repository via:
```
mkdir local-mirros
cd local-mirros
wget https://github.com/pingcap-incubator/tiup/blob/master/localmirrors.sh
sh localmirros.sh
```

**Comment by july2993** [comment]
you can use set TIUP_MIRRORS when using /docker now
